language: c
branches:
  only:
  - master

dist: xenial

cache:
  directories:
    - $HOME/.cabsnap

matrix:
  include:
    - env:
        GHC_VER=8.4.4
        CABAL_VER=2.2
        ALEX_VER=3.2.5
        HAPPY_VER=1.19.12
        STDLIB_VER=1.4
      addons:
        apt:
          packages:
            # Unfortunately we cannot use the X_VER variables here
            - cabal-install-2.2
            - ghc-8.4.4
          sources:
            - hvr-ghc

before_install:
  - export PATH=/opt/ghc/$GHC_VER/bin:/opt/cabal/$CABAL_VER/bin:/opt/alex/$ALEX_VER/bin:/opt/happy/$HAPPY_VER/bin:~/.cabal/bin/:$PATH;
  - export RTS_OPTIONS="+RTS -M6G -H6G -A128M -RTS"


install:
  - cabal update
  - sed -i 's/^jobs:/-- jobs:/' $HOME/.cabal/config

  # installing dependencies
  - cabal install alex-$ALEX_VER happy-$HAPPY_VER cpphs

  # installing Agda (only master)
  - cd ../
  - git clone https://github.com/agda/agda
  - cd agda
  - git checkout 8eb0d01811a663cf2b27b482b3b18690adfa094b
  - cabal install --only-dependencies --dry -v > $HOME/installplan.txt ;

  # checking if .ghc is still valid
  - sed -i -e '1,/^Resolving /d' $HOME/installplan.txt; cat $HOME/installplan.txt
  - touch $HOME/.cabsnap/installplan.txt
  - mkdir -p $HOME/.cabsnap/ghc $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin
  - if diff -u $HOME/.cabsnap/installplan.txt $HOME/installplan.txt;
    then
      echo "cabal build-cache HIT";
      rm -rfv .ghc;
      cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
      cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
    else
      echo "cabal build-cache MISS";
      rm -rf $HOME/.cabsnap;
      mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
    fi
  # install master
  - cabal install

  # snapshot package-db on cache miss
  - echo "snapshotting package-db to build-cache";
    mkdir $HOME/.cabsnap;
    cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
    cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin $HOME/installplan.txt $HOME/.cabsnap/;
  - cd ../

  # installing agda-stdlib
  - mkdir -p $HOME/.agda
  - cd $HOME/.agda
  - wget https://github.com/agda/agda-stdlib/archive/v$STDLIB_VER.tar.gz
  - tar -xzvf v$STDLIB_VER.tar.gz
  - mv agda-stdlib-$STDLIB_VER agda-stdlib
  - echo "~/.agda/agda-stdlib/standard-library.agda-lib" > libraries
  - cd -

  # doing things for this library
  - cd agda-categories
  - cp travis/* .

script:
  - find src/ -name '[^\.]*.agda' | sed -e 's|^src/[/]*|import |' -e 's|/|.|g' -e 's/.agda//' -e '/import Everything/d' | LC_COLLATE='C' sort > Everything.agda
  - cat Everything.agda >> index.agda
  - agda $RTS_OPTIONS -i. -i src/ Everything.agda
  - agda $RTS_OPTIONS -i. -i src/ index.agda
  - agda $RTS_OPTIONS -i. -i src/ --html index.agda
  # moving everything to the main directory
  - mv html/* .

after_success:
  # uploading to gh-pages
  - git init
  - git config --global user.name "Travis CI bot"
  - git config --global user.email "travis-ci-bot@travis.fake"
  - git remote add upstream https://$GH_TOKEN@github.com/agda/agda-categories.git &>/dev/null
  - git fetch upstream && git reset upstream/gh-pages
  - git add -f \*.html \*.css
  - git commit -m "Automatic HTML update via Travis"
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ];
    then git push -q upstream HEAD:gh-pages &>/dev/null;
    fi

notifications:
  email: false
